### PR TITLE
Support for mingw-w64 in gnu mode

### PR DESCRIPTION
**Pull request by martell**
I have submitted the patches from this PR to the llvm-commits mailing list :)

### CODE REVIEW

**Comment by procedural** [comment]
Woah, great job, Martell!

**Comment by ismail** [comment]
Can you rebase and put this on http://reviews.llvm.org/ so it can be reviewed?

**Comment by martell** [comment]
Hi @ismail,

I already sent it into llvm.
Along with 30 or so other patches.
They were in the middle of creating new section based linkers "COFF" and "ELF2" so this patch was not merged.
We apply it locally to msys2.
We will have to wait until ELF2 is finialised before redoing this work on the newer linkers.
This patch would not be allowed on the official 3.7.x repos as patches are only back ported from HEAD.
So locally applying is the only option

**Comment by dcci** [comment]
lld2 is stable, in fact it's now lld. Feel free to submit patches upstream and/or report bugs instead of using github.

**Pull request closed without merging**
